In [1]:
#Phase 1: load,explore & clean
#In this noyebook, im starting Phase 1 of the capstone project.
#I'll load the titanic dataset, take a quick look at it , and clean it up
#This includes fixing column types, filling missing values , removing duplicates,and capping extreme numbers so the data is ready for analysis.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [3]:
#load data
#we read the csv file into a dataframe and look at the first few rows.

In [4]:
#load data

url_train= "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df=pd.read_csv(url_train)

#show first 5 rows to see the data
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
## Step 1: Fix Data Types

#`Pclass` is numeric but represents categories, so we convert it to `category`.
#Embarked` is also categorical (port codes), convert to `category`.

In [6]:
def fix_data_types(df):
    df = df.copy()
    # Pclass is numeric but actually a category
    df["Pclass"] = df["Pclass"].astype("category")
    # Embarked is categorical (port codes)
    df["Embarked"] = df["Embarked"].astype("category")
    return df

In [7]:
## Step 2: Handle Missing Values

#- `Age`: fill missing with median (robust to outliers).
#- `Embarked`: fill missing with mode (most common value).
#- `Fare`: fill missing with median.
#- `Cabin`: too many missing values, drop the column.

In [8]:
def handle_missing_values(df):
    df = df.copy()
    df["Age"] = df["Age"].fillna(df["Age"].median())  # fill missing Age
    df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])  # fill missing Embarked
    df["Fare"] = df["Fare"].fillna(df["Fare"].median())  # fill missing Fare
    df = df.drop(columns=["Cabin"], errors="ignore")  # drop Cabin if exists, ignore if not
    return df

In [9]:
## Step 3: Remove Duplicates

#Check for and remove any duplicate rows.

In [10]:
def remove_duplicates(df):
    df = df.copy()
    # drop any duplicate rows if they exist
    df = df.drop_duplicates()
    return df

In [11]:
## Step 4: Cap Outliers

#- Cap `Fare` at the 99th percentile to avoid extreme values affecting analysis.

In [12]:
def cap_outliers(df):
    df = df.copy()
    # cap Fare at the 99th percentile to limit extreme values
    upper_fare = df["Fare"].quantile(0.99)
    df["Fare"] = np.where(df["Fare"] > upper_fare, upper_fare, df["Fare"])
    return df

In [13]:
## Step 5: Ensure Positive Fare

#- Keep only rows where Fare is zero or positive.

In [14]:
# -----------------------
def ensure_positive_fare(df):
    df = df.copy()
    # keep only rows where Fare is zero or positive
    df = df[df["Fare"] >= 0]
    return df

In [15]:
## Step 6: Combine All Steps

#We create a main function `clean_data()` that runs all the cleaning steps in order.

In [16]:
def clean_data(df):
    df = df.copy()
    # fix the data types first
    df = fix_data_types(df)
    # fill missing values and drop Cabin
    df = handle_missing_values(df)
    # remove duplicate rows if any
    df = remove_duplicates(df)
    # cap extreme Fare values at 99th percentile
    df = cap_outliers(df)
    # make sure Fare is not negative
    df = ensure_positive_fare(df)
    return df

In [17]:
## Step 7: Apply Cleaning and Check Results

In [18]:
df = clean_data(df)

# final checks after cleaning
assert df["Age"].isnull().sum() == 0, "There are missing values in Age!"
assert df["Fare"].isnull().sum() == 0, "There are missing values in Fare!"
assert (df["Fare"] >= 0).all(), "Some Fare values are negative!"
assert df.shape[1] == 11, f"Expected 11 columns, got {df.shape[1]}"

# Show final shape and first 5 rows
print("Final shape:", df.shape)
df.head()

Final shape: (891, 11)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S